# SQL Data Analysis

## DecodeLabs Internship – Week 3 Project

### Objective
The objective of this project is to perform SQL-based data analysis on an E-commerce dataset. Using SQL queries, we will extract meaningful business insights by applying filtering, sorting, grouping, and aggregation techniques.

### Skills Demonstrated
- SQL Fundamentals
- Data Querying
- Filtering Records using WHERE
- Sorting Data using ORDER BY
- Grouping Data using GROUP BY
- Aggregate Functions (COUNT, SUM, AVG, MAX, MIN)
- Business Insight Generation

### Dataset Overview
The dataset contains information about customer orders including product details, quantities, prices, payment methods, order status, referral sources, and total revenue generated.

### Project Goals
1. Explore the dataset using SQL queries.
2. Analyze customer purchasing behavior.
3. Identify top-performing products.
4. Examine payment method preferences.
5. Evaluate referral source effectiveness.
6. Generate business insights from aggregated data.
## Problem Statement

The objective of this project is to analyze an E-commerce dataset using SQL. By applying SQL operations such as SELECT, WHERE, ORDER BY, GROUP BY, and aggregate functions, meaningful business insights can be extracted regarding sales performance, customer behavior, payment preferences, and referral effectiveness.

## Load Dataset

In this section, we load the E-commerce dataset into a Pandas DataFrame and inspect the initial records to understand its structure and contents.

In [2]:
import pandas as pd

# Load dataset
df = pd.read_excel("Dataset for Data Analytics.xlsx")
# Display first 5 rows
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

## Dataset Overview

Before performing SQL analysis, it is important to understand the dataset's dimensions, column names, data types, and basic statistics.

In [3]:
# Dataset dimensions
print("Dataset Shape:", df.shape)

# Column names
print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (1200, 14)

Columns:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

In [ ]:

# Column names
print("\nColumns:")
print(df.columns.tolist())

In [4]:
# Data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

In [5]:
# Statistical summary
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [6]:
# Check missing values
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [7]:
# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

## Creating SQL Database

To perform SQL-based analysis, the dataset is converted into a SQLite database table. This allows us to execute SQL queries directly on the data and extract meaningful business insights using filtering, sorting, grouping, and aggregation operations.

In [8]:
import sqlite3

In [9]:
# Create SQLite connection
conn = sqlite3.connect('ecommerce.db')

# Convert DataFrame into SQL table
df.to_sql(
    name='orders',
    con=conn,
    if_exists='replace',
    index=False
)

print("Database and table created successfully!")

Database and table created successfully!

In [10]:
# Verify table creation
query = """
SELECT *
FROM orders
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

### Observation

The dataset has been successfully stored as a SQL table named **orders**. We can now perform SQL queries to analyze sales, customer behavior, payment methods, order status, and revenue trends.

## Basic SQL Queries

Basic SQL queries help us retrieve and inspect data from the database table. The SELECT statement is used to fetch records and specific columns from the dataset.

In [11]:
query = """
SELECT *
FROM orders
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23 00:00:00,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17 00:00:00,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12 00:00:00,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02 00:00:00,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
9,ORD200009,2023-11-21 00:00:00,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

### Observation

The query displays the first 10 records from the orders table, providing an overview of the available data and its structure.

In [12]:
query = """
SELECT OrderID, Product, Quantity, TotalPrice
FROM orders
LIMIT 10;
"""

pd.read_sql_query(query, conn)

     OrderID  Product  Quantity  TotalPrice
0  ORD200000  Monitor         5     2853.10
1  ORD200001    Phone         2      302.70
2  ORD200002   Tablet         5     2753.40
3  ORD200003    Chair         1      273.19
4  ORD200004  Printer         4     2504.04
5  ORD200005    Phone         2      491.72
6  ORD200006   Laptop         1      664.42
7  ORD200007  Monitor         5      747.75
8  ORD200008    Phone         2      268.56
9  ORD200009     Desk         4     2037.52

### Observation

Only the relevant columns are displayed, making the output more focused and easier to analyze.

In [13]:
query = """
SELECT DISTINCT Product
FROM orders;
"""

pd.read_sql_query(query, conn)

   Product
0  Monitor
1    Phone
2   Tablet
3    Chair
4  Printer
5   Laptop
6     Desk

### Observation

The DISTINCT keyword removes duplicate values and returns the list of unique products available in the dataset.

In [14]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM orders;
"""

pd.read_sql_query(query, conn)

   Total_Orders
0          1200

### Observation

This query calculates the total number of orders present in the dataset.

In [15]:
query = """
SELECT COUNT(DISTINCT CustomerID) AS Unique_Customers
FROM orders;
"""

pd.read_sql_query(query, conn)

   Unique_Customers
0              1189

### Observation

The query determines the number of unique customers who placed orders, helping us understand the customer base size.

## Data Filtering using WHERE Clause

The WHERE clause is used to filter records based on specific conditions. It helps extract relevant information from the dataset by selecting only those rows that satisfy the given criteria.

In [16]:
query = """
SELECT *
FROM orders
WHERE OrderStatus = 'Delivered';
"""

pd.read_sql_query(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200015,2023-07-17 00:00:00,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,NaN,Google,473.96
2,ORD200021,2024-11-17 00:00:00,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,NaN,Google,1371.80
3,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
4,ORD200025,2024-07-24 00:00:00,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,ORD201166,2023-07-31 00:00:00,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
227,ORD201168,2023-04-08 00:00:00,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
228,ORD201171,2023-08-28 00:00:00,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
229,ORD201187,2024-03-13 00:00:00,C26340,Desk,2,184.60,562 Main St,Gift Card,Delivered,TRK59962703,7,WINTER15,Email,369.20
230,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

### Observation

This query retrieves all orders that were successfully delivered to customers.

In [17]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
WHERE TotalPrice > 5000;
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [OrderID, Product, TotalPrice]
Index: []

### Observation

The query identifies high-value orders with a total price exceeding ₹5000.

In [18]:
query = """
SELECT OrderID, CustomerID, PaymentMethod, TotalPrice
FROM orders
WHERE PaymentMethod = 'Credit Card';
"""

pd.read_sql_query(query, conn)

       OrderID CustomerID PaymentMethod  TotalPrice
0    ORD200002     C81728   Credit Card     2753.40
1    ORD200005     C37249   Credit Card      491.72
2    ORD200009     C31946   Credit Card     2037.52
3    ORD200010     C43443   Credit Card     3129.85
4    ORD200013     C88348   Credit Card      604.47
..         ...        ...           ...         ...
229  ORD201174     C50159   Credit Card      667.02
230  ORD201178     C65107   Credit Card       70.24
231  ORD201179     C84630   Credit Card     2592.75
232  ORD201190     C46886   Credit Card     1849.17
233  ORD201195     C21126   Credit Card      107.04

[234 rows x 4 columns]

### Observation

This query filters orders that were paid using the Credit Card payment method.

In [19]:
query = """
SELECT OrderID, Product, Quantity
FROM orders
WHERE Quantity > 3;
"""

pd.read_sql_query(query, conn)

       OrderID  Product  Quantity
0    ORD200000  Monitor         5
1    ORD200002   Tablet         5
2    ORD200004  Printer         4
3    ORD200007  Monitor         5
4    ORD200009     Desk         4
..         ...      ...       ...
463  ORD201180    Chair         4
464  ORD201189   Tablet         5
465  ORD201191     Desk         4
466  ORD201198    Chair         4
467  ORD201199   Tablet         4

[468 rows x 3 columns]

### Observation

The query displays orders where customers purchased more than three units of a product.

In [20]:
query = """
SELECT OrderID, CustomerID, ReferralSource
FROM orders
WHERE ReferralSource = 'Social Media';
"""

pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [OrderID, CustomerID, ReferralSource]
Index: []

### Observation

This query identifies customers who reached the platform through social media referrals.

In [21]:
query = """
SELECT OrderID, Product, TotalPrice, OrderStatus
FROM orders
WHERE TotalPrice > 3000
AND OrderStatus = 'Delivered';
"""

pd.read_sql_query(query, conn)

     OrderID  Product  TotalPrice OrderStatus
0  ORD200361  Printer     3299.25   Delivered
1  ORD200632   Laptop     3390.80   Delivered
2  ORD200789   Tablet     3456.40   Delivered
3  ORD200837    Chair     3277.75   Delivered
4  ORD201065  Printer     3334.00   Delivered
5  ORD201079    Phone     3170.00   Delivered

### Observation

The query returns delivered orders with a total price greater than ₹3000.

In [22]:
query = """
SELECT OrderID, Product, OrderStatus
FROM orders
WHERE OrderStatus = 'Cancelled'
OR OrderStatus = 'Returned';
"""

pd.read_sql_query(query, conn)

       OrderID  Product OrderStatus
0    ORD200002   Tablet   Cancelled
1    ORD200003    Chair    Returned
2    ORD200006   Laptop    Returned
3    ORD200008    Phone   Cancelled
4    ORD200010   Tablet    Returned
..         ...      ...         ...
492  ORD201193   Tablet    Returned
493  ORD201195     Desk   Cancelled
494  ORD201196  Monitor   Cancelled
495  ORD201198    Chair   Cancelled
496  ORD201199   Tablet    Returned

[497 rows x 3 columns]

### Observation

This query displays orders that were either cancelled or returned.

## Sorting Data using ORDER BY

The ORDER BY clause is used to sort records in ascending (ASC) or descending (DESC) order. It helps identify top-performing products, highest-value orders, and other ranked business metrics.

In [23]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC;
"""

pd.read_sql_query(query, conn)

        OrderID  Product  TotalPrice
0     ORD200789   Tablet     3456.40
1     ORD201122  Monitor     3390.95
2     ORD200632   Laptop     3390.80
3     ORD200469    Chair     3384.90
4     ORD200328   Tablet     3370.20
...         ...      ...         ...
1195  ORD200336   Laptop       18.20
1196  ORD200542   Tablet       17.98
1197  ORD200240   Tablet       17.24
1198  ORD200863    Phone       14.06
1199  ORD201161    Phone       11.39

[1200 rows x 3 columns]

### Observation

The query sorts orders from highest to lowest total price, helping identify the most valuable transactions.

In [25]:
query = """
SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice ASC;
"""

pd.read_sql_query(query, conn)

        OrderID  Product  TotalPrice
0     ORD201161    Phone       11.39
1     ORD200863    Phone       14.06
2     ORD200240   Tablet       17.24
3     ORD200542   Tablet       17.98
4     ORD200336   Laptop       18.20
...         ...      ...         ...
1195  ORD200328   Tablet     3370.20
1196  ORD200469    Chair     3384.90
1197  ORD200632   Laptop     3390.80
1198  ORD201122  Monitor     3390.95
1199  ORD200789   Tablet     3456.40

[1200 rows x 3 columns]

### Observation

The query displays orders starting from the lowest transaction value.

In [26]:
query = """
SELECT DISTINCT Product
FROM orders
ORDER BY Product ASC;
"""

pd.read_sql_query(query, conn)

   Product
0    Chair
1     Desk
2   Laptop
3  Monitor
4    Phone
5  Printer
6   Tablet

### Observation

Products are arranged in alphabetical order, making them easier to browse and locate.

In [27]:
query = """
SELECT CustomerID, TotalPrice
FROM orders
ORDER BY TotalPrice DESC;
"""

pd.read_sql_query(query, conn)

     CustomerID  TotalPrice
0        C57276     3456.40
1        C38840     3390.95
2        C67260     3390.80
3        C13877     3384.90
4        C18404     3370.20
...         ...         ...
1195     C88174       18.20
1196     C49726       17.98
1197     C14983       17.24
1198     C98276       14.06
1199     C32570       11.39

[1200 rows x 2 columns]

### Observation

The query ranks customers based on their order value, highlighting high-spending customers.

In [28]:
query = """
SELECT OrderID, Product, Quantity
FROM orders
ORDER BY Quantity DESC;
"""

pd.read_sql_query(query, conn)

        OrderID  Product  Quantity
0     ORD200000  Monitor         5
1     ORD200002   Tablet         5
2     ORD200007  Monitor         5
3     ORD200010   Tablet         5
4     ORD200019  Monitor         5
...         ...      ...       ...
1195  ORD201184   Laptop         1
1196  ORD201185    Chair         1
1197  ORD201186  Monitor         1
1198  ORD201193   Tablet         1
1199  ORD201195     Desk         1

[1200 rows x 3 columns]

### Observation

This query identifies orders containing the largest quantities of products purchased.

In [29]:
query = """
SELECT OrderID, Date, Product, TotalPrice
FROM orders
ORDER BY Date DESC;
"""

pd.read_sql_query(query, conn)

        OrderID                 Date  Product  TotalPrice
0     ORD200256  2025-06-30 00:00:00    Chair      379.05
1     ORD201107  2025-06-30 00:00:00   Tablet      126.42
2     ORD200176  2025-06-28 00:00:00   Tablet     1723.32
3     ORD200773  2025-06-28 00:00:00    Phone     1024.66
4     ORD200882  2025-06-28 00:00:00    Phone      548.24
...         ...                  ...      ...         ...
1195  ORD200373  2023-01-02 00:00:00   Laptop     1023.45
1196  ORD200645  2023-01-02 00:00:00   Laptop      300.10
1197  ORD200112  2023-01-01 00:00:00  Monitor      410.60
1198  ORD200236  2023-01-01 00:00:00  Monitor      318.81
1199  ORD200848  2023-01-01 00:00:00    Chair     1291.70

[1200 rows x 4 columns]

### Observation

Orders are sorted from the most recent to the oldest based on the transaction date.

## Aggregate Functions Analysis

Aggregate functions are used to perform calculations on multiple rows of data and return a single summarized result. These functions help in understanding overall business performance, revenue generation, customer activity, and sales trends.

In [30]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM orders;
"""

pd.read_sql_query(query, conn)

   Total_Orders
0          1200

### Observation

This query calculates the total number of orders present in the dataset.

In [31]:
query = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM orders;
"""

pd.read_sql_query(query, conn)

   Total_Revenue
0     1264761.96

### Observation

The query computes the overall revenue generated from all customer orders.

In [32]:
query = """
SELECT AVG(TotalPrice) AS Average_Order_Value
FROM orders;
"""

pd.read_sql_query(query, conn)

   Average_Order_Value
0            1053.9683

### Observation

This query determines the average amount spent per order.

In [34]:
query = """
SELECT MAX(TotalPrice) AS Highest_Order_Value
FROM orders;
"""

pd.read_sql_query(query, conn)

   Highest_Order_Value
0               3456.4

### Observation

The query identifies the highest-value transaction in the dataset.

In [35]:
query = """
SELECT MIN(TotalPrice) AS Lowest_Order_Value
FROM orders;
"""

pd.read_sql_query(query, conn)

   Lowest_Order_Value
0               11.39

### Observation

This query returns the smallest transaction amount recorded in the dataset.

In [36]:
query = """
SELECT SUM(Quantity) AS Total_Quantity_Sold
FROM orders;
"""

pd.read_sql_query(query, conn)

   Total_Quantity_Sold
0                 3535

### Observation

The query calculates the total number of product units sold across all orders.

In [37]:
query = """
SELECT AVG(Quantity) AS Average_Quantity
FROM orders;
"""

pd.read_sql_query(query, conn)

   Average_Quantity
0          2.945833

### Observation

This query measures the average number of products purchased in each order.

## Grouping Data using GROUP BY

The GROUP BY clause is used to arrange data into groups based on one or more columns. It is commonly combined with aggregate functions to generate meaningful business insights such as revenue by product, orders by payment method, and customer spending patterns.

In [38]:
query = """
SELECT Product,
       SUM(TotalPrice) AS Total_Revenue
FROM orders
GROUP BY Product
ORDER BY Total_Revenue DESC;
"""

pd.read_sql_query(query, conn)

   Product  Total_Revenue
0    Chair      195620.11
1  Printer      195612.61
2   Laptop      192126.56
3   Tablet      186568.95
4  Monitor      175651.41
5     Desk      167459.93
6    Phone      151722.39

### Observation

This query calculates revenue generated by each product and ranks them from highest to lowest revenue.

In [39]:
query = """
SELECT PaymentMethod,
       COUNT(*) AS Total_Orders
FROM orders
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC;
"""

pd.read_sql_query(query, conn)

  PaymentMethod  Total_Orders
0        Online           258
1          Cash           246
2   Credit Card           234
3    Debit Card           232
4     Gift Card           230

### Observation

The query identifies the most preferred payment methods among customers.

In [40]:
query = """
SELECT OrderStatus,
       COUNT(*) AS Total_Orders
FROM orders
GROUP BY OrderStatus
ORDER BY Total_Orders DESC;
"""

pd.read_sql_query(query, conn)

  OrderStatus  Total_Orders
0   Cancelled           250
1    Returned           247
2     Pending           237
3     Shipped           235
4   Delivered           231

### Observation

This query shows the distribution of orders across different statuses such as Delivered, Shipped, Returned, and Cancelled.

In [41]:
query = """
SELECT ReferralSource,
       SUM(TotalPrice) AS Total_Revenue
FROM orders
GROUP BY ReferralSource
ORDER BY Total_Revenue DESC;
"""

pd.read_sql_query(query, conn)

  ReferralSource  Total_Revenue
0      Instagram      275285.45
1          Email      261808.55
2         Google      250441.48
3       Facebook      250410.90
4       Referral      226815.58

### Observation

The query evaluates which referral channels contribute the highest revenue to the business.

In [42]:
query = """
SELECT CustomerID,
       SUM(TotalPrice) AS Total_Spending
FROM orders
GROUP BY CustomerID
ORDER BY Total_Spending DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  CustomerID  Total_Spending
0     C38840         5723.23
1     C57276         3456.40
2     C67260         3390.80
3     C13877         3384.90
4     C18404         3370.20
5     C16775         3353.75
6     C65986         3352.40
7     C47778         3334.00
8     C59183         3322.55
9     C25276         3313.90

### Observation

This query identifies the top 10 customers based on their total spending amount.

In [43]:
query = """
SELECT Product,
       SUM(Quantity) AS Quantity_Sold
FROM orders
GROUP BY Product
ORDER BY Quantity_Sold DESC;
"""

pd.read_sql_query(query, conn)

   Product  Quantity_Sold
0    Chair            562
1  Printer            542
2   Laptop            535
3     Desk            508
4   Tablet            497
5  Monitor            480
6    Phone            411

### Observation

The query highlights the products with the highest sales volume.

In [44]:
query = """
SELECT PaymentMethod,
       AVG(TotalPrice) AS Average_Order_Value
FROM orders
GROUP BY PaymentMethod
ORDER BY Average_Order_Value DESC;
"""

pd.read_sql_query(query, conn)

  PaymentMethod  Average_Order_Value
0   Credit Card          1127.553974
1     Gift Card          1070.973565
2          Cash          1056.041829
3        Online          1017.220698
4    Debit Card          1001.556810

### Observation

This query compares the average spending of customers across different payment methods.

In [45]:
query = """
SELECT ReferralSource,
       AVG(TotalPrice) AS Average_Revenue
FROM orders
GROUP BY ReferralSource
ORDER BY Average_Revenue DESC;
"""

pd.read_sql_query(query, conn)

  ReferralSource  Average_Revenue
0       Facebook      1098.293421
1      Instagram      1062.878185
2          Email      1047.234200
3         Google      1039.176266
4       Referral      1021.691802

### Observation

The query helps identify which referral channels attract higher-value customers on average.

## Key Business Insights

Based on the SQL analysis performed on the E-commerce dataset, several important business insights were identified regarding customer behavior, product performance, revenue generation, and payment preferences.

### 1. Top Revenue Generating Products

Products generating the highest revenue contribute significantly to the overall business performance. These products should be prioritized in inventory planning, promotions, and marketing campaigns to maximize profitability.

### 2. Preferred Payment Methods

Analysis of payment methods reveals customer transaction preferences. Understanding these preferences helps businesses optimize payment options and improve customer experience.

### 3. Order Status Distribution

Most orders were successfully processed and delivered, while a smaller proportion were returned or cancelled. Monitoring these categories helps evaluate operational efficiency and customer satisfaction.

### 4. Customer Spending Patterns

A small group of customers contributes a significant portion of total revenue. Identifying these high-value customers can support loyalty programs and targeted marketing initiatives.

### 5. Referral Source Performance

Referral channels vary in their contribution to revenue and customer acquisition. The most effective sources should receive greater marketing focus to improve return on investment.

### 6. Product Demand Analysis

Products with the highest quantities sold indicate strong customer demand. These products should be monitored closely to ensure sufficient stock availability.

# Conclusion

This project demonstrated the use of SQL for analyzing an E-commerce dataset and extracting meaningful business insights. Various SQL operations including SELECT, WHERE, ORDER BY, GROUP BY, and aggregate functions were applied to explore customer behavior, sales performance, and operational trends.

Key findings included identifying top-selling products, analyzing customer spending patterns, evaluating payment method preferences, and measuring the effectiveness of referral sources. These insights can support better business decision-making and strategic planning.

Through this project, practical experience was gained in:
- SQL Query Writing
- Data Filtering and Sorting
- Data Aggregation
- Business Intelligence Reporting
- Data-Driven Decision Making

Overall, SQL proved to be an effective tool for transforming raw transactional data into actionable business insights.

In [46]:
# Close database connection
conn.close()